import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Abhay Gupta Portfolio App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="w-screen h-screen bg-gradient-to-b from-purple-300 to-blue-300 ">
          <div className="h-24">
          <Navbar />
          </div>
         <div className="h-[calc(100vh-96px)]">
         {children}
         </div>
        </div>
      </body>
    </html>
  );
}
